//
// Created by Luke Martin on 2023-03-29.
//

#ifndef WAVECOLLAPSESUDOKUSOLVER_INPUTWINDOW_H
#define WAVECOLLAPSESUDOKUSOLVER_INPUTWINDOW_H


class InputWindow {

};


#endif //WAVECOLLAPSESUDOKUSOLVER_INPUTWINDOW_H
